// Generated by i18nline.
import I18n from 'i18nline';

I18n.supportedLocales = ['cs','de','en','es','fr','hu','it'];
I18n.defaultLocale = 'en';

I18n.import = locale => {
	// we use a switch here so the import statements are statically
	// analyzable. the use of import() will make build tools generate
	// separate bundles which are downloaded on-demand.
	switch (locale) {
		case 'cs': return import(/* webpackChunkName: 'i18n.cs' */ './cs.json');
		case 'de': return import(/* webpackChunkName: 'i18n.de' */ './de.json');
		case 'en': return import(/* webpackChunkName: 'i18n.en' */ './en.json');
		case 'es': return import(/* webpackChunkName: 'i18n.es' */ './es.json');
		case 'fr': return import(/* webpackChunkName: 'i18n.fr' */ './fr.json');
		case 'hu': return import(/* webpackChunkName: 'i18n.hu' */ './hu.json');
		case 'it': return import(/* webpackChunkName: 'i18n.it' */ './it.json');
		default: return import(/* webpackChunkName: 'i18n.default' */ './default.json');
	}
};

if ((typeof module === 'object') && module.hot) {
	module.hot.accept('./cs.json', I18n.reload('cs'));
	module.hot.accept('./de.json', I18n.reload('de'));
	module.hot.accept('./en.json', I18n.reload('en'));
	module.hot.accept('./es.json', I18n.reload('es'));
	module.hot.accept('./fr.json', I18n.reload('fr'));
	module.hot.accept('./hu.json', I18n.reload('hu'));
	module.hot.accept('./it.json', I18n.reload('it'));
	module.hot.accept('./default.json', I18n.reload('default'));
}

export default I18n;
